=== Sonal-Raina/WTL_Assignments/Assignment3/employeedtd.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT employees (employee+)>
<!ELEMENT employee (id, name, address)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>

=== Sonal-Raina/WTL_Assignments/Assignment3/employeexml.xml
<?xml version="1.0" encoding="UTF-8"?>
 
<!DOCTYPE employees SYSTEM "employeedtd.dtd"> 

<employees>

    <employee>
        <id>101</id>
        <name>Amit Shinde</name>
        <address>Pune</address>
    </employee>
    <employee>
        <id>102</id>
        <name>Pranav Khairnar</name>
        <address>Mumbai</address>
    </employee>
    <employee>
        <id>104</id>
        <name>Abhi Mundada</name>
        <address>New Delhi</address>
    </employee> 

</employees>
